Repository komadesu/giftour, pull requests merged in 2020-12, with the labels that each got.

#41 create auth component and implement redirect
  resources/js/src/App.js
  resources/js/src/components/Auth.js
  resources/js/src/reducers/user.js
Labels: frontend

#42 Implement signup and login ajax
  app/Http/Kernel.php
  composer.json
  composer.lock
  config/cors.php
  resources/js/src/actions/auth.js
  resources/js/src/actions/index.js
  resources/js/src/actions/user.js
  resources/js/src/components/Login.js
  resources/js/src/components/Signup.js
  resources/js/src/reducers/auth.js
  resources/js/src/reducers/index.js
  resources/js/src/reducers/user.js
Labels: frontend

#43 Implement login redirect
  resources/js/src/components/Auth.js
  resources/js/src/components/Login.js
  resources/js/src/components/MyPage.js
Labels: frontend

#44 implement signup redirect
  resources/js/src/components/Header.js
  resources/js/src/components/Signup.js
Labels: frontend

#45 Implement logout
  resources/js/src/actions/auth.js
  resources/js/src/actions/user.js
  resources/js/src/components/Header.js
  resources/js/src/components/Login.js
  resources/js/src/components/Signup.js
  resources/js/src/reducers/auth.js
  resources/js/src/reducers/user.js
  resources/sass/_header.scss
Labels: frontend

#46 Impelement ajax
  app/Http/Controllers/Api/BookmarkController.php
  app/Http/Controllers/Api/GiftController.php
  resources/js/src/actions/archives.js
  resources/js/src/actions/bookmarks.js
  resources/js/src/actions/gifts.js
  resources/js/src/components/Gift.js
  resources/js/src/components/MyPage.js
  resources/js/src/components/Search.js
  resources/js/src/components/Timeline.js
  resources/js/src/reducers/archives.js
  resources/js/src/reducers/bookmarks.js
  resources/js/src/reducers/gifts.js
Labels: enhancement, frontend

#47 Implement post function
  resources/js/src/actions/auth.js
  resources/js/src/actions/gifts.js
  resources/js/src/actions/user.js
  resources/js/src/components/Form.js
  resources/js/src/components/Header.js
  resources/js/src/reducers/auth.js
  resources/js/src/reducers/gifts.js
  resources/js/src/reducers/user.js
  resources/sass/_form.scss
  resources/sass/_header.scss
Labels: frontend

#48 Implement ajax
  app/Http/Controllers/Api/GiftController.php
  resources/js/src/components/MyPage.js
Labels: frontend

#49 implement proper search function from both of Index and Timeline comp…
  app/Http/Controllers/Api/GiftController.php
  resources/js/src/actions/gifts.js
  resources/js/src/components/Index.js
  resources/js/src/components/Search.js
  resources/js/src/components/Timeline.js
Labels: frontend

#52 Implement post function
  resources/js/src/actions/archives.js
  resources/js/src/actions/gifts.js
  resources/js/src/components/Archives.js
  resources/js/src/components/Bookmarks.js
  resources/js/src/components/Form.js
  resources/js/src/reducers/archives.js
  resources/js/src/reducers/bookmarks.js
Labels: frontend

#50 Implement bookmark function
  app/Http/Controllers/Api/BookmarkController.php
  resources/js/src/actions/bookmarks.js
  resources/js/src/components/Gift.js
  resources/js/src/components/Header.js
  resources/js/src/reducers/bookmarks.js
Labels: frontend

#53 implement redirect to timeline after create gift
  resources/js/src/components/Form.js
Labels: frontend

#55 Implement delete function
  app/Http/Controllers/Api/GiftController.php
  resources/js/src/actions/archives.js
  resources/js/src/actions/gifts.js
  resources/js/src/components/Edit.js
  resources/js/src/components/MyPage.js
  resources/js/src/reducers/archives.js
  resources/js/src/reducers/gifts.js
Labels: frontend

#54 display empty message if any gifts exist
  resources/js/src/components/Archives.js
  resources/js/src/components/Bookmarks.js
  resources/js/src/components/MyPage.js
  resources/js/src/components/Timeline.js
  resources/sass/_mypage.scss
Labels: frontend

#57 display archive and saved gift correctly in mypage when each item is …
  resources/js/src/components/MyPage.js
Labels: frontend

#59 add URL to README
  readme.md
Labels: infra

#60 change url for app
  readme.md
Labels: infra
